[target.aarch64-linux-android]
linker = "D:/Tools/android-ndk-r22b/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android26-clang.cmd"

[target.armv7-linux-androideabi]
linker = "D:/Tools/android-ndk-r22b/toolchains/llvm/prebuilt/windows-x86_64/bin/armv7a-linux-androideabi26-clang.cmd"
