[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[dependencies]
lexer = { path = "../lexer" }
ast = { path = "../ast" }
diagnostic = { path = "../diagnostic", features = ["global_instance"] }
